name: Print Secret
run-name: ${{ github.actor }} is doing push
on:
  push:
    branches: [ "tomzi0402-patch-1" ]

jobs:
  print-secret:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app    

    steps:
      - uses: actions/checkout@v4
      - name: Print secret variable
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          echo "$API_ENDPOINT" | sed 's/./& /g'
      - name: List out workspace
        run: ls ${{ github.workspace }}
      - name: Check the content before replacing by secret variables
        run: head -n 50 src/App.js
      - name: Replaced by secret variables
        run: sed -i 's/%API_ENDPOINT%/${{ secrets.API_ENDPOINT }}/g' src/App.js
      - name: Check the content after replacing by secret variables
        run: head -n 50 src/App.js        
