name: Replace secret variables
run-name: ${{ github.actor }} is doing push
on:
  push:
    branches: [ "tomzi0402-patch-1" ]

jobs:
  APP-replace-secret-variables:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - shell: bash
      env: 
        API_ENDPOINT: ${{ secrets.API_ENDPOINT}}
      run: |
        echo "$env:API_ENDPOINT"
