name: Print Secret
run-name: ${{ github.actor }} is doing push
on:
  push:
    branches: [ "tomzi0402-patch-1" ]

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret variable
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          echo ${{secrets.API_ENDPOINT}} | sed 's/./& /g'
          # echo "::add-mask::" # Add this to unmask
          # echo "API_ENDPOINT is: $API_ENDPOINT"
